/**
 * Nine fictional campus applicants from the vendor's sample reports.
 *
 * Eight were placed below the shortlist line by Orbis SocialFit; one was lifted
 * above it. Each shows a different way a social-media signal can mislead.
 * Names, colleges, posts and profiles are invented. Any resemblance to a real
 * person is coincidental.
 */
import type { Candidate } from "./types";

export const CANDIDATES: Candidate[] = [
  {
    id: "meera",
    name: "Meera Krishnan",
    degree: "B.E. Computer Science",
    college: "Sri Valluvar College of Engineering",
    collegeTier: 2,
    city: "Coimbatore",
    state: "Tamil Nadu",
    graduationYear: 2027,
    aptitude: 68,
    presence: "active",
    postLanguage: "Tamil and English",
    application: {
      statedLinks: ["instagram.com/meera.codes"],
      notes: "Part-time online maths tutor for Class 10 students, evenings, since 2025.",
    },
    matchedProfile: {
      displayName: "Meera Krishnan",
      city: "Coimbatore",
      college: "Sri Valluvar College of Engineering",
      graduationYear: 2027,
      matchBasis: "Link supplied in the application",
    },
    posts: [
      {
        id: "m1",
        platform: "Instagram",
        postedAt: "2026-08-14T01:42:00+05:30",
        language: "English",
        text: "Two students cleared their pre-board maths today. Worth every late night.",
        publishedBy: "self",
        triggered: ["S01"],
      },
      {
        id: "m2",
        platform: "Instagram",
        postedAt: "2026-09-02T00:58:00+05:30",
        language: "Tamil",
        text: "Finally finished the DBMS assignment. Sleeping now, alarm at 6.",
        original: "DBMS assignment mudinjiduchu. Ippo thoonga poren, 6 manikku alarm.",
        publishedBy: "self",
        triggered: ["S01", "S02"],
      },
      {
        id: "m3",
        platform: "Instagram",
        postedAt: "2026-09-20T02:15:00+05:30",
        language: "English",
        text: "Session with my Grade 10 batch ran over again. Quadratics are hard at midnight.",
        publishedBy: "self",
        triggered: ["S01"],
      },
    ],
    signalValues: { S01: 1, S02: 0.3, S08: 0.1, S09: 0.2 },
    headline: "Flagged for low discipline because she posts after midnight.",
    reviewNote:
      "Her application says she tutors school students online in the evenings. The late posts are about that work. Posting time has no link to how she would do this job, and the review removes the signal.",
  },
  {
    id: "arjun",
    name: "Arjun Verma",
    degree: "B.Tech Information Technology",
    college: "Awadh Institute of Technology",
    collegeTier: 3,
    city: "Lucknow",
    state: "Uttar Pradesh",
    graduationYear: 2027,
    aptitude: 70,
    presence: "active",
    postLanguage: "Hinglish",
    application: {
      statedLinks: ["x.com/arjunv_codes"],
      notes: "Captain, college cricket team. Built a scoring app used by the inter-college league.",
    },
    matchedProfile: {
      displayName: "Arjun Verma",
      city: "Lucknow",
      college: "Awadh Institute of Technology",
      graduationYear: 2027,
      matchBasis: "Link supplied in the application",
    },
    posts: [
      {
        id: "a1",
        platform: "X",
        postedAt: "2026-09-10T22:04:00+05:30",
        language: "Hinglish",
        text: "Brother, what an innings. Kohli absolutely tore the bowlers apart today.",
        original: "Bhai kya innings thi. Kohli ne aaj gendbaazon ki dhajjiyan uda di.",
        publishedBy: "self",
        triggered: ["S02"],
      },
      {
        id: "a2",
        platform: "X",
        postedAt: "2026-09-12T19:30:00+05:30",
        language: "Hinglish",
        text: "Our league scoring app crossed 2,000 users. Crazy stuff, guys.",
        original: "Apna league scoring app 2,000 users cross kar gaya. Pagalpan hai yaar.",
        publishedBy: "self",
        triggered: ["S02"],
      },
      {
        id: "a3",
        platform: "X",
        postedAt: "2026-09-18T23:40:00+05:30",
        language: "Hinglish",
        text: "Final over, need 12. If we lose this I'm going to kill someone (joking).",
        original: "Last over, 12 chahiye. Haar gaye toh kisi ko maar dunga (mazaak).",
        publishedBy: "self",
        triggered: ["S02"],
      },
    ],
    signalValues: { S01: 0.2, S02: 1, S08: 0.1, S09: 0.3, S10: 0.05 },
    headline: "Flagged for aggressive language. It was cricket banter in Hinglish.",
    reviewNote:
      "The vendor's text model reads English only. 'Dhajjiyan uda di' is an everyday idiom for a dominant performance, and the third post says it is a joke. The review restricts this signal: only explicit threats or harassment, read by a person who understands the language, may be considered.",
  },
  {
    id: "fatima",
    name: "Fatima Shaikh",
    degree: "B.E. Electronics and Communication",
    college: "Deccan College of Engineering and Technology",
    collegeTier: 2,
    city: "Hyderabad",
    state: "Telangana",
    graduationYear: 2027,
    aptitude: 70,
    presence: "active",
    postLanguage: "English and Urdu",
    application: {
      statedLinks: ["instagram.com/fatima.builds"],
      notes: "Final-year project: low-cost air-quality sensor network for schools.",
    },
    matchedProfile: {
      displayName: "Fatima Shaikh",
      city: "Hyderabad",
      college: "Deccan College of Engineering and Technology",
      graduationYear: 2027,
      matchBasis: "Link supplied in the application",
    },
    posts: [
      {
        id: "f1",
        platform: "Instagram",
        postedAt: "2026-03-21T19:10:00+05:30",
        language: "English",
        text: "Eid Mubarak from all of us! Ammi's sheer khurma, as always, won the day.",
        publishedBy: "self",
        triggered: ["S07"],
      },
      {
        id: "f2",
        platform: "Instagram",
        postedAt: "2026-03-05T04:20:00+05:30",
        language: "Urdu",
        text: "Sehri with the family before a long lab day.",
        original: "Ghar walon ke saath sehri, phir lamba lab ka din.",
        publishedBy: "self",
        triggered: ["S07", "S01"],
      },
      {
        id: "f3",
        platform: "Instagram",
        postedAt: "2026-08-30T17:45:00+05:30",
        language: "English",
        text: "Our air-quality sensors are live in three schools. Proud of this team.",
        publishedBy: "self",
        triggered: [],
      },
    ],
    signalValues: { S01: 0.3, S07: 1, S08: 0.1, S09: 0.5, S10: 0.1 },
    headline: "Scored low on culture fit. The score was driven by her Eid posts.",
    reviewNote:
      "The culture-fit model compares content with the existing workforce's profiles, so festival content from a minority faith scores as 'dissimilar'. A pre-dawn Sehri post also triggered the late-night signal. This is religion entering a hiring decision through a proxy, and the review removes the signal.",
  },
  {
    id: "rahul",
    name: "Rahul Sharma",
    degree: "B.Tech Computer Science",
    college: "Aravali Institute of Engineering",
    collegeTier: 2,
    city: "Jaipur",
    state: "Rajasthan",
    graduationYear: 2027,
    aptitude: 74,
    presence: "minimal",
    postLanguage: "English",
    application: {
      statedLinks: [],
      notes: "No social media links supplied.",
    },
    matchedProfile: {
      displayName: "Rahul Sharma",
      city: "New Delhi",
      college: "University of Delhi",
      graduationYear: 2019,
      matchBasis: "Name search and photo similarity (vendor confidence: 'high')",
    },
    posts: [
      {
        id: "r1",
        platform: "Instagram",
        postedAt: "2026-07-04T23:55:00+05:30",
        language: "English",
        text: "Saturday night, rooftop, the usual suspects. 🍻",
        publishedBy: "self",
        triggered: ["S05", "S01"],
      },
      {
        id: "r2",
        platform: "X",
        postedAt: "2026-08-15T11:20:00+05:30",
        language: "English",
        text: "Marching today. If you're not angry, you're not paying attention.",
        publishedBy: "self",
        triggered: ["S06"],
      },
      {
        id: "r3",
        platform: "Instagram",
        postedAt: "2026-09-06T01:30:00+05:30",
        language: "English",
        text: "Worst client call of my life, 7 years into this job and still.",
        publishedBy: "self",
        triggered: ["S02", "S01"],
      },
    ],
    signalValues: { S01: 0.7, S02: 0.6, S05: 1, S06: 0.6, S08: 0.5, S09: 0.9 },
    headline: "Flagged as a lifestyle risk. The profile belongs to a different Rahul Sharma.",
    reviewNote:
      "The vendor matched a Delhi University graduate from 2019 who mentions seven years in a job. The applicant is a 2027 graduate from Jaipur who supplied no links. None of the three checkable details match. Using this profile breaks the DPDP duty to keep data used in a decision accurate.",
  },
  {
    id: "kavya",
    name: "Kavya Behera",
    degree: "B.Tech Computer Science",
    college: "Rushikulya Institute of Technology",
    collegeTier: 3,
    city: "Berhampur",
    state: "Odisha",
    graduationYear: 2027,
    aptitude: 76,
    presence: "none",
    postLanguage: "None",
    application: {
      statedLinks: [],
      notes: "Does not use social media. University topper, CSE 2027 batch.",
    },
    matchedProfile: null,
    posts: [],
    signalValues: { S12: 1 },
    headline: "Marked down for 'insufficient data'. She does not use social media.",
    reviewNote:
      "Kavya has the highest aptitude score of the nine and no social media at all. The tool treats having nothing to read as a risk, so it marks her down 14 points. Choosing not to post says nothing about ability, and the review removes the penalty.",
  },
  {
    id: "dev",
    name: "Dev Patil",
    degree: "B.E. Mechanical Engineering",
    college: "Sahyadri College of Engineering",
    collegeTier: 2,
    city: "Pune",
    state: "Maharashtra",
    graduationYear: 2027,
    aptitude: 67,
    presence: "active",
    postLanguage: "Marathi and English",
    application: {
      statedLinks: ["instagram.com/dev.makes"],
      notes: "Robotics club lead. Switching to software through Kestrel's engineering track.",
    },
    matchedProfile: {
      displayName: "Dev Patil",
      city: "Pune",
      college: "Sahyadri College of Engineering",
      graduationYear: 2027,
      matchBasis: "Link supplied in the application",
    },
    posts: [
      {
        id: "d1",
        platform: "Instagram",
        postedAt: "2026-06-05T18:10:00+05:30",
        language: "English",
        text: "Climate march today. Proud of this crowd. @dev.makes @sneha.r @omkar_08",
        publishedBy: "tagged",
        triggered: ["S06"],
      },
      {
        id: "d2",
        platform: "Instagram",
        postedAt: "2026-09-01T20:00:00+05:30",
        language: "Marathi",
        text: "The robotics team qualified for nationals!",
        original: "Robotics team national sathi qualify jhali!",
        publishedBy: "self",
        triggered: ["S02"],
      },
    ],
    signalValues: { S02: 0.2, S06: 1, S08: 0.2, S09: 0.4, S10: 0.05 },
    headline: "Flagged as a controversy risk. A friend tagged him in a protest photo.",
    reviewNote:
      "Dev did not post the protest photo; a friend did and tagged him. The DPDP exemption for public data covers only what a person makes public themselves, so this content does not fall under it. Political expression is also not a lawful basis for a hiring decision. The review removes the signal.",
  },
  {
    id: "priya",
    name: "Priya Raman",
    degree: "B.E. Computer Science",
    college: "Kaveri Institute of Technology",
    collegeTier: 2,
    city: "Chennai",
    state: "Tamil Nadu",
    graduationYear: 2027,
    aptitude: 70,
    presence: "private",
    postLanguage: "Private account",
    application: {
      statedLinks: ["github.com/priyaraman-dev"],
      notes: "Two open-source contributions to a Python data library.",
    },
    matchedProfile: {
      displayName: "Priya Raman",
      city: "Chennai",
      college: "Kaveri Institute of Technology",
      graduationYear: 2027,
      matchBasis: "Link supplied in the application",
    },
    posts: [
      {
        id: "p1",
        platform: "Facebook",
        postedAt: "2026-07-12T12:30:00+05:30",
        language: "English",
        text: "So happy to announce our daughter Priya's engagement! Wedding next spring. 💐",
        publishedBy: "tagged",
        triggered: ["S11"],
      },
    ],
    signalValues: { S10: 0.2, S11: 1, S12: 0.8, S13: 0.5 },
    headline: "Rated a high attrition risk because of an engagement announcement.",
    reviewNote:
      "Her own account is private. The tool found an engagement post by a family member and predicted she would relocate and leave. The vendor's attrition model learned this pattern from women's past exits. Marital status is not a basis for hiring, and gender discrimination in recruitment is barred by the Code on Wages, 2019. The review removes the signal.",
  },
  {
    id: "sandeep",
    name: "Sandeep Yadav",
    degree: "B.Tech Information Technology",
    college: "Malwa Institute of Technology",
    collegeTier: 2,
    city: "Bhopal",
    state: "Madhya Pradesh",
    graduationYear: 2027,
    aptitude: 69,
    presence: "active",
    postLanguage: "Hindi and English",
    application: {
      statedLinks: ["x.com/sandeep_y"],
      notes: "Interested in the data-engineering track.",
    },
    matchedProfile: {
      displayName: "Sandeep Yadav",
      city: "Bhopal",
      college: "Malwa Institute of Technology",
      graduationYear: 2027,
      matchBasis: "Link supplied in the application",
    },
    posts: [
      {
        id: "s1",
        platform: "X",
        postedAt: "2026-08-22T21:15:00+05:30",
        language: "English",
        text: "CAT mock 14: 96.2 percentile. Slowly getting there.",
        publishedBy: "self",
        triggered: ["S03"],
      },
      {
        id: "s2",
        platform: "X",
        postedAt: "2026-09-14T22:40:00+05:30",
        language: "Hinglish",
        text: "Placements plus CAT prep at the same time, the struggle is real.",
        original: "Placement aur CAT prep ek saath, struggle real hai bhai.",
        publishedBy: "self",
        triggered: ["S03", "S02"],
      },
    ],
    signalValues: { S02: 0.3, S03: 1, S08: 0.2, S09: 0.4, S10: 0.1 },
    headline: "Predicted not to join because he is preparing for CAT.",
    reviewNote:
      "This is the one signal with a real business link: further-study plans do affect joining. But the less intrusive way is to ask every candidate directly at offer stage and record the answer. That is fairer, because quiet candidates with the same plans are asked too, and more accurate, because plans change. The review restricts the signal and replaces it with the question.",
  },
  {
    id: "aditya",
    name: "Aditya Malhotra",
    degree: "B.Tech Computer Science",
    college: "National Institute of Technology, North Campus",
    collegeTier: 1,
    city: "New Delhi",
    state: "Delhi",
    graduationYear: 2027,
    aptitude: 60,
    presence: "active",
    postLanguage: "English",
    application: {
      statedLinks: ["linkedin.com/in/adityam", "github.com/adityam"],
      notes: "Two internships. Follows Kestrel's careers page; three seniors work at Kestrel.",
    },
    matchedProfile: {
      displayName: "Aditya Malhotra",
      city: "New Delhi",
      college: "National Institute of Technology, North Campus",
      graduationYear: 2027,
      matchBasis: "Link supplied in the application",
    },
    posts: [
      {
        id: "ad1",
        platform: "LinkedIn",
        postedAt: "2026-09-03T10:00:00+05:30",
        language: "English",
        text: "Grateful to the Kestrel alumni who mentored me through placement season.",
        publishedBy: "self",
        triggered: ["S10", "S09"],
      },
      {
        id: "ad2",
        platform: "Instagram",
        postedAt: "2026-08-10T20:30:00+05:30",
        language: "English",
        text: "Weekend in Goa with the batch. 🌊",
        publishedBy: "self",
        triggered: ["S05"],
      },
    ],
    signalValues: { S04: 0.3, S05: 0.3, S08: 0.9, S09: 1, S10: 0.8, S13: 0.7 },
    headline: "Lifted above the line by followers, English posts and Kestrel connections.",
    reviewNote:
      "Aditya has the lowest aptitude score of the nine, but his reach, his English posts and his network at Kestrel add about 28 points. None of those measure ability. The tool did not only push some candidates down; it pulled others up, and it did so along lines of college and background.",
  },
];

export const CANDIDATE_BY_ID: Record<string, Candidate> = Object.fromEntries(
  CANDIDATES.map((c) => [c.id, c])
);
