/**
 * The thirteen signals Orbis SocialFit reads, with the facts the review
 * recorded about each.
 *
 * `vendorClaim`, `feeds`, `direction` and `weight` come from the vendor's
 * brochure. `facts` are the review's own findings — each written so a reader
 * can disagree with a specific sentence rather than with a score.
 */
import type { VendorSignal } from "./types";

export const SIGNALS: VendorSignal[] = [
  {
    id: "S01",
    name: "Late-night posting",
    vendorClaim: "Posting between midnight and 5 a.m. indicates low discipline.",
    feeds: "reliability",
    direction: -1,
    weight: 8,
    facts: {
      jobLink: "none",
      jobLinkReason:
        "When someone posts says nothing about how they work. Night shifts, caregiving, study, tutoring and time-zone work all produce late posts.",
      proxies: [
        { trait: "health", strength: "weak", basis: "Sleep patterns can reflect medical conditions." },
        { trait: "religion", strength: "weak", basis: "Pre-dawn activity rises during Ramadan." },
      ],
      identityRisk: "low",
      identityReason: "Timestamps belong to the account that posted.",
      source: "self",
      audience: "social",
      sourceReason: "Candidates post for friends, not for employers.",
      coverage: "even",
      coverageReason: "Applies to anyone who posts publicly.",
      alternative: null,
      alternativeEquivalent: false,
      legalQuestion: null,
    },
    evidence: ["van-iddekinge-2016", "wp29-opinion-2-2017", "puttaswamy-proportionality"],
  },
  {
    id: "S02",
    name: "Slang and profanity",
    vendorClaim: "Casual or offensive language indicates low professionalism.",
    feeds: "professionalism",
    direction: -1,
    weight: 10,
    facts: {
      jobLink: "indirect",
      jobLinkReason:
        "Workplace conduct matters, but how someone talks with friends online is a weak guide to how they behave at work. Genuine threats or harassment are a different matter.",
      proxies: [
        { trait: "language", strength: "weak", basis: "Code-mixed Hindi-English is flagged more often by English-trained models." },
      ],
      identityRisk: "low",
      identityReason: "Text belongs to the account that posted it.",
      source: "self",
      audience: "social",
      sourceReason: "Informal posts are written for friends.",
      coverage: "excludes",
      coverageReason:
        "The vendor's text model is English-only. Hinglish and regional-language posts are misread; idioms such as 'dhajjiyan uda di' (tore it apart) are scored as aggression.",
      alternative:
        "A trained person reviews only content that a candidate published themselves and that shows explicit threats, harassment or hate, and the candidate may respond.",
      alternativeEquivalent: false,
      legalQuestion: null,
    },
    evidence: ["dpdp-accuracy", "eu-ai-act-annex-iii", "van-iddekinge-2016"],
  },
  {
    id: "S03",
    name: "Higher-studies preparation",
    vendorClaim: "Posts about CAT, GATE or GRE preparation mean the candidate is unlikely to join.",
    feeds: "reliability",
    direction: -1,
    weight: 12,
    facts: {
      jobLink: "indirect",
      jobLinkReason:
        "Plans for further study are genuinely relevant to whether someone joins. This is the signal with the clearest business link.",
      proxies: [],
      identityRisk: "low",
      identityReason: "Usually self-authored posts.",
      source: "self",
      audience: "social",
      sourceReason: "Posted to friends and study groups, not to employers.",
      coverage: "uneven",
      coverageReason: "Only visible for candidates who post about their plans; quiet candidates with the same plans are scored as safe.",
      alternative:
        "Ask every candidate at offer stage about their plans and joining date, and record the answer.",
      alternativeEquivalent: true,
      legalQuestion: null,
    },
    evidence: ["puttaswamy-proportionality", "dpdp-consent-notice", "wp29-opinion-2-2017"],
  },
  {
    id: "S04",
    name: "Mentions of other job offers",
    vendorClaim: "Posts celebrating offers from other companies mean the candidate is unlikely to join.",
    feeds: "reliability",
    direction: -1,
    weight: 8,
    facts: {
      jobLink: "indirect",
      jobLinkReason: "Competing offers do affect joining, so the signal has some business relevance.",
      proxies: [],
      identityRisk: "low",
      identityReason: "Usually self-authored posts.",
      source: "self",
      audience: "social",
      sourceReason: "Shared with friends and family.",
      coverage: "uneven",
      coverageReason: "Tier-1 campus candidates receive and post about more offers, so they are penalised more often.",
      alternative: "A joining-confirmation conversation at offer stage, plus joining incentives.",
      alternativeEquivalent: false,
      legalQuestion:
        "Whether reading candidates' posts about competing employers is covered by the DPDP publicly-available exemption, and whether penalising a candidate for considering other offers is acceptable practice for Kestrel.",
    },
    evidence: ["dpdp-public-exemption", "dpdp-legitimate-use-employment", "puttaswamy-proportionality"],
  },
  {
    id: "S05",
    name: "Party and alcohol photos",
    vendorClaim: "Images of alcohol or parties indicate a lifestyle risk.",
    feeds: "professionalism",
    direction: -1,
    weight: 10,
    facts: {
      jobLink: "none",
      jobLinkReason: "Lawful social life outside work is not a measure of job performance.",
      proxies: [
        { trait: "religion", strength: "weak", basis: "Abstinence varies by faith, so the signal falls unevenly across communities." },
      ],
      identityRisk: "high",
      identityReason: "Photos are often posted by friends, and image matching confuses people with similar names and faces.",
      source: "mixed",
      audience: "social",
      sourceReason: "Many party photos are posted by friends who tag the candidate.",
      coverage: "even",
      coverageReason: "Applies to anyone photographed publicly.",
      alternative: null,
      alternativeEquivalent: false,
      legalQuestion: null,
    },
    evidence: ["van-iddekinge-2016", "dpdp-public-exemption", "dpdp-accuracy"],
  },
  {
    id: "S06",
    name: "Political or protest content",
    vendorClaim: "Political posts or attendance at protests indicate a controversy risk.",
    feeds: "professionalism",
    direction: -1,
    weight: 10,
    facts: {
      jobLink: "none",
      jobLinkReason: "Lawful political expression has no bearing on software delivery.",
      proxies: [
        { trait: "political_opinion", strength: "direct", basis: "The signal is political opinion." },
        { trait: "religion", strength: "weak", basis: "Some protests are community-specific." },
        { trait: "caste", strength: "weak", basis: "Some protests are caste-specific." },
      ],
      identityRisk: "medium",
      identityReason: "Crowd photos are frequently mis-tagged.",
      source: "mixed",
      audience: "social",
      sourceReason: "Protest photos are often posted by others who tag attendees.",
      coverage: "even",
      coverageReason: "Applies to anyone photographed publicly.",
      alternative: null,
      alternativeEquivalent: false,
      legalQuestion: null,
    },
    evidence: ["gdpr-art9", "wp29-opinion-2-2017", "puttaswamy-proportionality"],
  },
  {
    id: "S07",
    name: "Religious and festival content",
    vendorClaim: "Part of the culture-fit model: content dissimilar to current employees' profiles lowers fit.",
    feeds: "culture_fit",
    direction: -1,
    weight: 12,
    facts: {
      jobLink: "none",
      jobLinkReason: "Religious practice has no bearing on job performance.",
      proxies: [
        { trait: "religion", strength: "direct", basis: "The model compares religious content with the existing workforce's, so minority-faith content scores as dissimilar." },
      ],
      identityRisk: "low",
      identityReason: "Usually self-authored posts.",
      source: "self",
      audience: "social",
      sourceReason: "Shared with family and community.",
      coverage: "even",
      coverageReason: "Applies to anyone who posts publicly.",
      alternative: null,
      alternativeEquivalent: false,
      legalQuestion: null,
    },
    evidence: ["gdpr-art9", "amazon-recruiting-2018", "puttaswamy-proportionality"],
  },
  {
    id: "S08",
    name: "Follower count and engagement",
    vendorClaim: "Large audiences and high engagement indicate strong communication skills.",
    feeds: "culture_fit",
    direction: 1,
    weight: 8,
    facts: {
      jobLink: "none",
      jobLinkReason: "Social reach measures popularity, not the ability to communicate at work.",
      proxies: [
        { trait: "socioeconomic", strength: "strong", basis: "Reach tracks urban background, device access and leisure time." },
        { trait: "gender", strength: "weak", basis: "Women more often keep accounts private, so they show smaller audiences." },
      ],
      identityRisk: "low",
      identityReason: "Counts belong to the account.",
      source: "self",
      audience: "social",
      sourceReason: "Audiences are built socially, not professionally.",
      coverage: "excludes",
      coverageReason: "Candidates with private or no accounts score zero.",
      alternative: "Assess communication directly in the interview and the written exercise.",
      alternativeEquivalent: true,
      legalQuestion: null,
    },
    evidence: ["van-iddekinge-2016", "eeoc-four-fifths", "puttaswamy-proportionality"],
  },
  {
    id: "S09",
    name: "Language of posts",
    vendorClaim: "Posting in English indicates client-ready communication.",
    feeds: "culture_fit",
    direction: 1,
    weight: 10,
    facts: {
      jobLink: "indirect",
      jobLinkReason:
        "English matters for client work, but the language someone uses with friends is not a test of their English.",
      proxies: [
        { trait: "region", strength: "strong", basis: "Post language follows home state." },
        { trait: "language", strength: "direct", basis: "The signal is language." },
        { trait: "socioeconomic", strength: "weak", basis: "English-medium schooling tracks family income." },
      ],
      identityRisk: "low",
      identityReason: "Language belongs to the account.",
      source: "self",
      audience: "social",
      sourceReason: "Candidates write to friends in the language they share.",
      coverage: "uneven",
      coverageReason: "Penalises candidates from non-Hindi, non-English-speaking regions most.",
      alternative: "Test English directly in the written exercise and interview.",
      alternativeEquivalent: true,
      legalQuestion: null,
    },
    evidence: ["eeoc-four-fifths", "nyc-ll144", "puttaswamy-proportionality"],
  },
  {
    id: "S10",
    name: "Network overlap with employees",
    vendorClaim: "Following Kestrel pages or being connected to Kestrel employees indicates culture fit.",
    feeds: "culture_fit",
    direction: 1,
    weight: 10,
    facts: {
      jobLink: "none",
      jobLinkReason: "Knowing current employees says nothing about ability.",
      proxies: [
        { trait: "college_tier", strength: "strong", basis: "Existing employees cluster in a few colleges, so their networks do too." },
        { trait: "socioeconomic", strength: "weak", basis: "Professional networks track family background." },
      ],
      identityRisk: "low",
      identityReason: "Connections belong to the account.",
      source: "self",
      audience: "social",
      sourceReason: "Connections are made socially.",
      coverage: "uneven",
      coverageReason: "Candidates from colleges Kestrel has rarely hired from start behind.",
      alternative: null,
      alternativeEquivalent: false,
      legalQuestion: null,
    },
    evidence: ["amazon-recruiting-2018", "eeoc-four-fifths", "nyc-ll144"],
  },
  {
    id: "S11",
    name: "Engagement and wedding posts",
    vendorClaim: "Engagement or wedding posts predict relocation and early attrition.",
    feeds: "reliability",
    direction: -1,
    weight: 12,
    facts: {
      jobLink: "none",
      jobLinkReason: "Marital plans are not a lawful or reliable basis for predicting someone's career.",
      proxies: [
        { trait: "marital_status", strength: "direct", basis: "The signal is marital status." },
        { trait: "gender", strength: "strong", basis: "The vendor's model learned the attrition pattern from women's past exits, so it applies the penalty mainly to women." },
      ],
      identityRisk: "medium",
      identityReason: "Family members often post the photos.",
      source: "mixed",
      audience: "social",
      sourceReason: "Wedding and engagement photos are commonly posted by family.",
      coverage: "even",
      coverageReason: "Applies to anyone photographed publicly.",
      alternative: null,
      alternativeEquivalent: false,
      legalQuestion: null,
    },
    evidence: ["code-on-wages-gender", "amazon-recruiting-2018", "gdpr-art9"],
  },
  {
    id: "S12",
    name: "Little or no social media",
    vendorClaim: "Insufficient data is treated as elevated risk and lowers the score.",
    feeds: "reliability",
    direction: -1,
    weight: 14,
    facts: {
      jobLink: "none",
      jobLinkReason: "Choosing not to use social media says nothing about ability or reliability.",
      proxies: [
        { trait: "socioeconomic", strength: "strong", basis: "Rural and lower-income candidates are less active online." },
        { trait: "gender", strength: "strong", basis: "Women more often keep accounts private or stay off public platforms." },
        { trait: "age", strength: "weak", basis: "Older career-changers post less." },
      ],
      identityRisk: "low",
      identityReason: "No content is involved.",
      source: "self",
      audience: "social",
      sourceReason: "The absence of content is the signal.",
      coverage: "excludes",
      coverageReason: "Penalises precisely the candidates the tool cannot see.",
      alternative: null,
      alternativeEquivalent: false,
      legalQuestion: null,
    },
    evidence: ["dpdp-consent-notice", "eeoc-four-fifths", "wp29-opinion-2-2017"],
  },
  {
    id: "S13",
    name: "Professional profile consistency",
    vendorClaim: "LinkedIn and GitHub activity that matches the résumé confirms claimed skills and projects.",
    feeds: "reliability",
    direction: 1,
    weight: 12,
    facts: {
      jobLink: "direct",
      jobLinkReason: "Checking that claimed projects and skills exist is directly related to the job.",
      proxies: [],
      identityRisk: "medium",
      identityReason: "The vendor finds profiles by name search, which can match the wrong person. Using only links the candidate supplies removes the risk.",
      source: "self",
      audience: "professional",
      sourceReason: "Professional profiles are published so that employers will read them.",
      coverage: "uneven",
      coverageReason: "Tier-3 college students are less likely to have GitHub portfolios, so absence must not count against anyone.",
      alternative: null,
      alternativeEquivalent: false,
      legalQuestion: null,
    },
    evidence: ["dpdp-public-exemption", "dpdp-accuracy", "wp29-opinion-2-2017"],
  },
];

export const SIGNAL_BY_ID: Record<string, VendorSignal> = Object.fromEntries(
  SIGNALS.map((s) => [s.id, s])
);
